require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'nuMarket' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  use_flipper!('Flipper' => '0.58.0')
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'nuMarket-tvOS' do
  # Pods for nuMarket-tvOS

  target 'nuMarket-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
